#print_head "Copy MongoDB Repo file"
#cp ${script_location}/files/mongodb.repo /etc/yum.repos.d/mongodb.repo &>>${LOG}
#status_check
#
#print_head "Install MongoDB"
#yum install mongodb-org -y &>>${LOG}
#status_check
#
#status_check
#
#print_head "Enable MongoDB"
#systemctl enable mongod &>>${LOG}
#status_check
#
#print_head "Start MongoDB"
#systemctl restart mongod &>>${LOG}
#status_check

- name: Copy MongoDB Yum Repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo


- name: Install Mongodb Server
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update MongoDB Listen Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes