#
#print_head " Copy Roboshop Nginx Configure File"
#cp ${script_location}/files/nginx-roboshop.conf /etc/nginx/default.d/roboshop.conf &>>${LOG}
#status_check
#
#print_head " Enable Nginx"
#systemctl enable nginx &>>${LOG}
#status_check
#
#print_head " Restart Nginx"
#systemctl restart nginx &>>${LOG}
#
- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Romeve old HTTP Documents
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Create a HTTP document directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name:  downloaded frontend content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy RoboShop config file to nginx
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf