- name: Disable Mysql 8 version
  ansible.builtin.shell: dnf module disable mysql -y


- name: Copy MySQL Repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL Server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: Start Mysql Service
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: Reset Default Database Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ${root_mysql_password}



