- name: Configure NodeJS repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name:  downloaded App content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes

- name: Romeve old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Extract App Content
  ansible.builtin.file:
    path: /app
    state: directory

- name: Install NodJS Dependencies
  community.general.npm:
    path: /app
    state: latest

- name: Copy System File
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

- name: Start Catalogue Service
  ansible.builtin.systemd:
    state: started
    name: catalogue
    enabled: yes
    daemon_reload: yes
    state: restarted
