- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Romeve old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create App Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name:  downloaded  {{component}} App content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes