
- name: Install GoLang
  ansible.builtin.yum:
    name:  maven
    state: installed

- name: App Pre-Req
  ansible.builtin.include_tasks: "app-prereq.yml"


- name:  Download GoLang Dependencies
  ansible.builtin.package:
    name: golang
    path: /app
    state: latest

- name: Systemd Setup
  ansible.builtin.include_tasks: "systemd.yml"

- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load




