- name: Install Python 3
  ansible.builtin.yum:
    name:
    - python36
    - gcc
    - python3-devel
    state: installed


- name: App Pre-Req
  ansible.builtin.include_tasks: "app-prereq.yml"


- name: Download python Dependencies
  community.general.pip:
    requirement: /app/requirement.txt
    exucutable: pip3.6

- name: Systemd Setup
  ansible.builtin.include_tasks: "systemd.yml"

- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load






