- name: Copy SystemD File
  ansible.builtin.templates:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: Start {{component}} Service
  ansible.builtin.systemd:
    name: "{{component}}"
    daemon_reload: yes
    enabled: yes
    state: restarted

